"""Google Drive (+ Docs / Sheets / Slides) integration."""
from modulex_integrations.tools.google_drive.manifest import manifest
from modulex_integrations.tools.google_drive.tools import (
    add_slide,
    append_to_google_doc,
    create_folder,
    create_google_doc,
    create_google_sheet,
    create_google_slides,
    create_text_file,
    format_sheet_cells,
    format_sheet_text,
    read_google_doc,
    read_google_sheet,
    read_google_slides,
    update_google_doc,
    update_google_sheet,
    update_slide_content,
    update_text_file,
)

TOOLS = (
    create_text_file,
    update_text_file,
    create_folder,
    create_google_doc,
    read_google_doc,
    update_google_doc,
    append_to_google_doc,
    create_google_sheet,
    read_google_sheet,
    update_google_sheet,
    format_sheet_cells,
    format_sheet_text,
    create_google_slides,
    read_google_slides,
    add_slide,
    update_slide_content,
)

__all__ = [
    "TOOLS",
    "add_slide",
    "append_to_google_doc",
    "create_folder",
    "create_google_doc",
    "create_google_sheet",
    "create_google_slides",
    "create_text_file",
    "format_sheet_cells",
    "format_sheet_text",
    "manifest",
    "read_google_doc",
    "read_google_sheet",
    "read_google_slides",
    "update_google_doc",
    "update_google_sheet",
    "update_slide_content",
    "update_text_file",
]
