"""Ashby integration — discovered by modulex via the ``modulex.tools``
entry point.

Public surface: ``manifest`` (IntegrationManifest) and ``TOOLS``
(tuple of LangChain ``StructuredTool`` objects, one per action).
"""
from modulex_integrations.tools.ashby.manifest import manifest
from modulex_integrations.tools.ashby.tools import (
    add_candidate_tag,
    change_application_stage,
    create_application,
    create_candidate,
    create_note,
    get_application,
    get_candidate,
    get_job,
    get_job_posting,
    get_offer,
    list_applications,
    list_archive_reasons,
    list_candidate_tags,
    list_candidates,
    list_custom_fields,
    list_departments,
    list_interviews,
    list_job_postings,
    list_jobs,
    list_locations,
    list_notes,
    list_offers,
    list_openings,
    list_sources,
    list_users,
    remove_candidate_tag,
    search_candidates,
    update_candidate,
)

TOOLS = (
    list_candidates,
    get_candidate,
    create_candidate,
    update_candidate,
    search_candidates,
    list_jobs,
    get_job,
    create_note,
    list_notes,
    list_applications,
    get_application,
    create_application,
    change_application_stage,
    add_candidate_tag,
    remove_candidate_tag,
    list_offers,
    get_offer,
    list_sources,
    list_candidate_tags,
    list_archive_reasons,
    list_custom_fields,
    list_departments,
    list_locations,
    list_job_postings,
    get_job_posting,
    list_openings,
    list_users,
    list_interviews,
)

__all__ = [
    "TOOLS",
    "add_candidate_tag",
    "change_application_stage",
    "create_application",
    "create_candidate",
    "create_note",
    "get_application",
    "get_candidate",
    "get_job",
    "get_job_posting",
    "get_offer",
    "list_applications",
    "list_archive_reasons",
    "list_candidate_tags",
    "list_candidates",
    "list_custom_fields",
    "list_departments",
    "list_interviews",
    "list_job_postings",
    "list_jobs",
    "list_locations",
    "list_notes",
    "list_offers",
    "list_openings",
    "list_sources",
    "list_users",
    "manifest",
    "remove_candidate_tag",
    "search_candidates",
    "update_candidate",
]
