"""Google Slides integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.google_slides.manifest import manifest
from modulex_integrations.tools.google_slides.tools import (
    create_image,
    create_page_element,
    create_presentation,
    create_slide,
    create_table,
    delete_page_element,
    delete_slide,
    delete_table_column,
    delete_table_row,
    find_presentation,
    insert_table_columns,
    insert_table_rows,
    insert_text,
    insert_text_into_table,
    merge_data,
    refresh_chart,
    replace_all_text,
)

TOOLS = (
    create_image,
    create_page_element,
    create_presentation,
    create_slide,
    create_table,
    delete_page_element,
    delete_slide,
    delete_table_column,
    delete_table_row,
    find_presentation,
    insert_table_columns,
    insert_table_rows,
    insert_text,
    insert_text_into_table,
    merge_data,
    refresh_chart,
    replace_all_text,
)

__all__ = [
    "TOOLS",
    "create_image",
    "create_page_element",
    "create_presentation",
    "create_slide",
    "create_table",
    "delete_page_element",
    "delete_slide",
    "delete_table_column",
    "delete_table_row",
    "find_presentation",
    "insert_table_columns",
    "insert_table_rows",
    "insert_text",
    "insert_text_into_table",
    "manifest",
    "merge_data",
    "refresh_chart",
    "replace_all_text",
]
