"""LinkedIn integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.linkedin.manifest import manifest
from modulex_integrations.tools.linkedin.tools import (
    create_comment,
    create_image_post_organization,
    create_image_post_user,
    create_like_on_share,
    create_text_post_organization,
    create_text_post_user,
    delete_post,
    fetch_ad_account,
    get_current_member_profile,
    get_member_profile,
    get_multiple_member_profiles,
    get_org_member_access,
    get_organization_access_control,
    get_organization_administrators,
    get_profile_picture_fields,
    retrieve_comments_on_comments,
    retrieve_comments_shares,
    search_organization,
)

TOOLS = (
    create_comment,
    create_image_post_organization,
    create_image_post_user,
    create_like_on_share,
    create_text_post_organization,
    create_text_post_user,
    delete_post,
    fetch_ad_account,
    get_current_member_profile,
    get_member_profile,
    get_multiple_member_profiles,
    get_org_member_access,
    get_organization_access_control,
    get_organization_administrators,
    get_profile_picture_fields,
    retrieve_comments_on_comments,
    retrieve_comments_shares,
    search_organization,
)

__all__ = [
    "TOOLS",
    "create_comment",
    "create_image_post_organization",
    "create_image_post_user",
    "create_like_on_share",
    "create_text_post_organization",
    "create_text_post_user",
    "delete_post",
    "fetch_ad_account",
    "get_current_member_profile",
    "get_member_profile",
    "get_multiple_member_profiles",
    "get_org_member_access",
    "get_organization_access_control",
    "get_organization_administrators",
    "get_profile_picture_fields",
    "manifest",
    "retrieve_comments_on_comments",
    "retrieve_comments_shares",
    "search_organization",
]
