"""Zendesk integration."""
from modulex_integrations.tools.zendesk.manifest import manifest
from modulex_integrations.tools.zendesk.tools import (
    add_ticket_tags,
    create_ticket,
    delete_ticket,
    get_article,
    get_macro,
    get_ticket,
    get_user,
    list_articles,
    list_locales,
    list_macros,
    list_ticket_comments,
    list_tickets,
    remove_ticket_tags,
    search_tickets,
    set_custom_fields,
    set_ticket_tags,
    update_ticket,
)

TOOLS = (
    create_ticket,
    update_ticket,
    delete_ticket,
    get_ticket,
    list_tickets,
    search_tickets,
    add_ticket_tags,
    set_ticket_tags,
    remove_ticket_tags,
    list_ticket_comments,
    set_custom_fields,
    get_user,
    list_locales,
    list_macros,
    get_macro,
    list_articles,
    get_article,
)

__all__ = [
    "TOOLS",
    "add_ticket_tags",
    "create_ticket",
    "delete_ticket",
    "get_article",
    "get_macro",
    "get_ticket",
    "get_user",
    "list_articles",
    "list_locales",
    "list_macros",
    "list_ticket_comments",
    "list_tickets",
    "manifest",
    "remove_ticket_tags",
    "search_tickets",
    "set_custom_fields",
    "set_ticket_tags",
    "update_ticket",
]
