"""SEMrush integration."""
from modulex_integrations.tools.semrush.manifest import manifest
from modulex_integrations.tools.semrush.tools import (
    api_units_balance,
    backlinks,
    backlinks_domains,
    batch_keyword_overview,
    broad_match_keywords,
    competitors,
    domain_organic_keywords,
    domain_overview,
    domain_paid_keywords,
    keyword_ads_history,
    keyword_difficulty,
    keyword_organic_results,
    keyword_overview,
    keyword_overview_single_db,
    keyword_paid_results,
    phrase_questions,
    related_keywords,
    traffic_sources,
    traffic_summary,
)

TOOLS = (
    domain_overview,
    domain_organic_keywords,
    domain_paid_keywords,
    competitors,
    backlinks,
    backlinks_domains,
    keyword_overview,
    keyword_overview_single_db,
    batch_keyword_overview,
    related_keywords,
    keyword_organic_results,
    keyword_paid_results,
    keyword_ads_history,
    broad_match_keywords,
    phrase_questions,
    keyword_difficulty,
    traffic_summary,
    traffic_sources,
    api_units_balance,
)

__all__ = [
    "TOOLS",
    "api_units_balance",
    "backlinks",
    "backlinks_domains",
    "batch_keyword_overview",
    "broad_match_keywords",
    "competitors",
    "domain_organic_keywords",
    "domain_overview",
    "domain_paid_keywords",
    "keyword_ads_history",
    "keyword_difficulty",
    "keyword_organic_results",
    "keyword_overview",
    "keyword_overview_single_db",
    "keyword_paid_results",
    "manifest",
    "phrase_questions",
    "related_keywords",
    "traffic_sources",
    "traffic_summary",
]
