"""Twilio integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.twilio.manifest import manifest
from modulex_integrations.tools.twilio.tools import (
    check_verification_token,
    create_verification_service,
    delete_call,
    delete_message,
    download_recording_media,
    get_call,
    get_message,
    get_transcripts,
    list_calls,
    list_message_media,
    list_messages,
    list_phone_numbers,
    list_transcripts,
    make_phone_call,
    phone_number_lookup,
    send_message,
    send_sms_verification,
)

TOOLS = (
    send_message,
    make_phone_call,
    get_message,
    delete_message,
    list_messages,
    list_message_media,
    get_call,
    delete_call,
    list_calls,
    download_recording_media,
    phone_number_lookup,
    send_sms_verification,
    check_verification_token,
    create_verification_service,
    list_transcripts,
    get_transcripts,
    list_phone_numbers,
)

__all__ = [
    "TOOLS",
    "check_verification_token",
    "create_verification_service",
    "delete_call",
    "delete_message",
    "download_recording_media",
    "get_call",
    "get_message",
    "get_transcripts",
    "list_calls",
    "list_message_media",
    "list_messages",
    "list_phone_numbers",
    "list_transcripts",
    "make_phone_call",
    "manifest",
    "phone_number_lookup",
    "send_message",
    "send_sms_verification",
]
