"""Google Calendar integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.google_calendar.manifest import manifest
from modulex_integrations.tools.google_calendar.tools import (
    add_attendees_to_event,
    create_event,
    delete_event,
    get_calendar,
    get_current_user,
    get_date_time,
    get_event,
    list_calendars,
    list_color_id_options,
    list_event_instances,
    list_events,
    query_free_busy_calendars,
    quick_add_event,
    update_event,
    update_event_instance,
    update_following_instances,
)

TOOLS = (
    add_attendees_to_event,
    create_event,
    delete_event,
    get_calendar,
    get_current_user,
    get_date_time,
    get_event,
    list_calendars,
    list_color_id_options,
    list_event_instances,
    list_events,
    query_free_busy_calendars,
    quick_add_event,
    update_event,
    update_event_instance,
    update_following_instances,
)

__all__ = [
    "TOOLS",
    "add_attendees_to_event",
    "create_event",
    "delete_event",
    "get_calendar",
    "get_current_user",
    "get_date_time",
    "get_event",
    "list_calendars",
    "list_color_id_options",
    "list_event_instances",
    "list_events",
    "manifest",
    "query_free_busy_calendars",
    "quick_add_event",
    "update_event",
    "update_event_instance",
    "update_following_instances",
]
