"""Salesforce integration."""
from modulex_integrations.tools.salesforce.manifest import manifest
from modulex_integrations.tools.salesforce.tools import (
    add_contact_to_campaign,
    add_lead_to_campaign,
    create_account,
    create_case,
    create_contact,
    create_lead,
    create_opportunity,
    create_record,
    create_task,
    delete_record,
    describe_object,
    get_record,
    list_objects,
    soql_query,
    sosl_search,
    update_record,
)

TOOLS = (
    soql_query,
    sosl_search,
    get_record,
    create_record,
    update_record,
    delete_record,
    create_account,
    create_contact,
    create_lead,
    create_opportunity,
    create_task,
    create_case,
    add_contact_to_campaign,
    add_lead_to_campaign,
    describe_object,
    list_objects,
)

__all__ = [
    "TOOLS",
    "add_contact_to_campaign",
    "add_lead_to_campaign",
    "create_account",
    "create_case",
    "create_contact",
    "create_lead",
    "create_opportunity",
    "create_record",
    "create_task",
    "delete_record",
    "describe_object",
    "get_record",
    "list_objects",
    "manifest",
    "soql_query",
    "sosl_search",
    "update_record",
]
