"""WooCommerce integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.woocommerce.manifest import manifest
from modulex_integrations.tools.woocommerce.tools import (
    add_order_note,
    create_customer,
    create_order,
    create_product,
    create_refund,
    delete_order,
    get_customer,
    get_order,
    get_order_note,
    get_product,
    list_order_notes,
    list_orders,
    list_payment_method_options,
    list_products,
    search_customers,
    update_order_status,
    update_product,
)

TOOLS = (
    create_order,
    get_order,
    list_orders,
    delete_order,
    update_order_status,
    create_product,
    update_product,
    get_product,
    list_products,
    search_customers,
    get_customer,
    create_customer,
    add_order_note,
    get_order_note,
    list_order_notes,
    create_refund,
    list_payment_method_options,
)

__all__ = [
    "TOOLS",
    "add_order_note",
    "create_customer",
    "create_order",
    "create_product",
    "create_refund",
    "delete_order",
    "get_customer",
    "get_order",
    "get_order_note",
    "get_product",
    "list_order_notes",
    "list_orders",
    "list_payment_method_options",
    "list_products",
    "manifest",
    "search_customers",
    "update_order_status",
    "update_product",
]
