"""Grafana integration — discovered by modulex via the ``modulex.tools``
entry point.

Public surface: ``manifest`` (IntegrationManifest) and ``TOOLS`` (tuple
of LangChain ``StructuredTool`` objects, one per action).
"""
from modulex_integrations.tools.grafana.manifest import manifest
from modulex_integrations.tools.grafana.tools import (
    check_data_source_health,
    create_alert_rule,
    create_annotation,
    create_contact_point,
    create_dashboard,
    create_folder,
    delete_alert_rule,
    delete_annotation,
    delete_dashboard,
    delete_folder,
    get_alert_rule,
    get_dashboard,
    get_data_source,
    get_folder,
    get_health,
    list_alert_rules,
    list_annotations,
    list_contact_points,
    list_dashboards,
    list_data_sources,
    list_folders,
    update_alert_rule,
    update_annotation,
    update_dashboard,
    update_folder,
)

TOOLS = (
    list_dashboards,
    get_dashboard,
    create_dashboard,
    update_dashboard,
    delete_dashboard,
    list_alert_rules,
    get_alert_rule,
    create_alert_rule,
    update_alert_rule,
    delete_alert_rule,
    list_contact_points,
    create_contact_point,
    create_annotation,
    list_annotations,
    update_annotation,
    delete_annotation,
    list_data_sources,
    get_data_source,
    check_data_source_health,
    list_folders,
    create_folder,
    get_folder,
    update_folder,
    delete_folder,
    get_health,
)

__all__ = [
    "TOOLS",
    "check_data_source_health",
    "create_alert_rule",
    "create_annotation",
    "create_contact_point",
    "create_dashboard",
    "create_folder",
    "delete_alert_rule",
    "delete_annotation",
    "delete_dashboard",
    "delete_folder",
    "get_alert_rule",
    "get_dashboard",
    "get_data_source",
    "get_folder",
    "get_health",
    "list_alert_rules",
    "list_annotations",
    "list_contact_points",
    "list_dashboards",
    "list_data_sources",
    "list_folders",
    "manifest",
    "update_alert_rule",
    "update_annotation",
    "update_dashboard",
    "update_folder",
]
