"""Microsoft Outlook integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.microsoft_outlook.manifest import manifest
from modulex_integrations.tools.microsoft_outlook.tools import (
    add_label_to_email,
    approve_workflow,
    create_contact,
    create_draft_email,
    create_draft_reply,
    download_attachment,
    find_contacts,
    find_email,
    find_shared_folder_email,
    get_current_user,
    get_message,
    list_contacts,
    list_folders,
    list_important_mail,
    list_labels,
    move_email_to_folder,
    remove_label_from_email,
    reply_to_email,
    send_email,
    update_contact,
)

TOOLS = (
    add_label_to_email,
    approve_workflow,
    create_contact,
    create_draft_email,
    create_draft_reply,
    download_attachment,
    find_contacts,
    find_email,
    find_shared_folder_email,
    get_current_user,
    get_message,
    list_contacts,
    list_folders,
    list_important_mail,
    list_labels,
    move_email_to_folder,
    remove_label_from_email,
    reply_to_email,
    send_email,
    update_contact,
)

__all__ = [
    "TOOLS",
    "add_label_to_email",
    "approve_workflow",
    "create_contact",
    "create_draft_email",
    "create_draft_reply",
    "download_attachment",
    "find_contacts",
    "find_email",
    "find_shared_folder_email",
    "get_current_user",
    "get_message",
    "list_contacts",
    "list_folders",
    "list_important_mail",
    "list_labels",
    "manifest",
    "move_email_to_folder",
    "remove_label_from_email",
    "reply_to_email",
    "send_email",
    "update_contact",
]
