"""Mailchimp integration."""
from modulex_integrations.tools.mailchimp.manifest import manifest
from modulex_integrations.tools.mailchimp.tools import (
    add_member_to_segment,
    add_note_to_subscriber,
    add_or_update_subscriber,
    create_campaign,
    create_list,
    delete_campaign,
    delete_list,
    delete_subscriber,
    get_campaign,
    get_campaign_report,
    get_campaigns,
    get_list,
    get_list_members,
    get_lists,
    get_member_tags,
    get_segments,
    get_subscriber,
    send_campaign,
    update_member_tags,
)

TOOLS = (
    get_lists,
    get_list,
    create_list,
    delete_list,
    get_list_members,
    get_subscriber,
    add_or_update_subscriber,
    delete_subscriber,
    get_campaigns,
    get_campaign,
    create_campaign,
    delete_campaign,
    send_campaign,
    get_campaign_report,
    get_member_tags,
    update_member_tags,
    add_note_to_subscriber,
    get_segments,
    add_member_to_segment,
)

__all__ = [
    "TOOLS",
    "add_member_to_segment",
    "add_note_to_subscriber",
    "add_or_update_subscriber",
    "create_campaign",
    "create_list",
    "delete_campaign",
    "delete_list",
    "delete_subscriber",
    "get_campaign",
    "get_campaign_report",
    "get_campaigns",
    "get_list",
    "get_list_members",
    "get_lists",
    "get_member_tags",
    "get_segments",
    "get_subscriber",
    "manifest",
    "send_campaign",
    "update_member_tags",
]
