"""Telegram Bot integration."""
from modulex_integrations.tools.telegram.manifest import manifest
from modulex_integrations.tools.telegram.tools import (
    ban_chat_member,
    create_chat_invite_link,
    delete_message,
    edit_text_message,
    forward_message,
    get_chat,
    get_chat_administrators,
    get_chat_member_count,
    get_me,
    get_updates,
    pin_message,
    send_audio,
    send_document,
    send_photo,
    send_text_message,
    send_video,
    unban_chat_member,
)

TOOLS = (
    send_text_message,
    send_photo,
    send_document,
    send_video,
    send_audio,
    forward_message,
    edit_text_message,
    delete_message,
    pin_message,
    get_chat_member_count,
    get_chat_administrators,
    get_updates,
    ban_chat_member,
    unban_chat_member,
    create_chat_invite_link,
    get_chat,
    get_me,
)

__all__ = [
    "TOOLS",
    "ban_chat_member",
    "create_chat_invite_link",
    "delete_message",
    "edit_text_message",
    "forward_message",
    "get_chat",
    "get_chat_administrators",
    "get_chat_member_count",
    "get_me",
    "get_updates",
    "manifest",
    "pin_message",
    "send_audio",
    "send_document",
    "send_photo",
    "send_text_message",
    "send_video",
    "unban_chat_member",
]
