"""Notion integration."""
from modulex_integrations.tools.notion.manifest import manifest
from modulex_integrations.tools.notion.tools import (
    append_blocks,
    create_comment,
    create_database,
    create_database_item,
    create_page,
    delete_block,
    get_block,
    get_block_children,
    get_bot_user,
    get_comments,
    get_database,
    get_page,
    get_user,
    list_users,
    query_database,
    search,
    update_block,
    update_database,
    update_page,
)

TOOLS = (
    search,
    create_page,
    get_page,
    update_page,
    query_database,
    get_database,
    create_database,
    update_database,
    create_database_item,
    get_block,
    get_block_children,
    append_blocks,
    update_block,
    delete_block,
    list_users,
    get_user,
    get_bot_user,
    create_comment,
    get_comments,
)

__all__ = [
    "TOOLS",
    "append_blocks",
    "create_comment",
    "create_database",
    "create_database_item",
    "create_page",
    "delete_block",
    "get_block",
    "get_block_children",
    "get_bot_user",
    "get_comments",
    "get_database",
    "get_page",
    "get_user",
    "list_users",
    "manifest",
    "query_database",
    "search",
    "update_block",
    "update_database",
    "update_page",
]
