"""AWS integration — discovered via the ``modulex.tools`` entry point."""
from modulex_integrations.tools.aws.manifest import manifest
from modulex_integrations.tools.aws.tools import (
    cloudwatch_logs_put_log_event,
    dynamodb_create_table,
    dynamodb_execute_statement,
    dynamodb_get_item,
    dynamodb_put_item,
    dynamodb_query,
    dynamodb_scan,
    dynamodb_update_item,
    dynamodb_update_table,
    eventbridge_send_event,
    lambda_create_function,
    lambda_invoke_function,
    list_region_options,
    redshift_create_rows,
    redshift_delete_rows,
    redshift_query_database,
    redshift_update_rows,
    s3_generate_presigned_url,
    s3_upload_base64_as_file,
    sns_send_message,
    sqs_send_message,
)

TOOLS = (
    cloudwatch_logs_put_log_event,
    dynamodb_create_table,
    dynamodb_execute_statement,
    dynamodb_get_item,
    dynamodb_put_item,
    dynamodb_query,
    dynamodb_scan,
    dynamodb_update_item,
    dynamodb_update_table,
    eventbridge_send_event,
    lambda_create_function,
    lambda_invoke_function,
    list_region_options,
    redshift_create_rows,
    redshift_delete_rows,
    redshift_query_database,
    redshift_update_rows,
    s3_generate_presigned_url,
    s3_upload_base64_as_file,
    sns_send_message,
    sqs_send_message,
)

__all__ = [
    "TOOLS",
    "cloudwatch_logs_put_log_event",
    "dynamodb_create_table",
    "dynamodb_execute_statement",
    "dynamodb_get_item",
    "dynamodb_put_item",
    "dynamodb_query",
    "dynamodb_scan",
    "dynamodb_update_item",
    "dynamodb_update_table",
    "eventbridge_send_event",
    "lambda_create_function",
    "lambda_invoke_function",
    "list_region_options",
    "manifest",
    "redshift_create_rows",
    "redshift_delete_rows",
    "redshift_query_database",
    "redshift_update_rows",
    "s3_generate_presigned_url",
    "s3_upload_base64_as_file",
    "sns_send_message",
    "sqs_send_message",
]
